### ISSUE TITLE
fix "1 pages" 

### ISSUE THREAD

**Issue by eleanorkonik** [isaaclyman/novel-word-count-obsidian#1]
For files that only have "1 page" worth of text, it would be neat if it could say "1 page" instead of "1 pages" 😅

Although honestly I'd love a way to just have it say "1p" or "250w" so it takes up less space.

**Comment by isaaclyman** [comment]
I agree on page/pages, good catch.

Is space at a premium in the file explorer? I didn't think about that, but it makes sense that some users would have long file names or folder trees. Let me think about this one for a moment and I'll publish an update.

**Comment by eleanorkonik** [comment]
I have very long file names 😅 lots of stuff like this: https://publish.obsidian.md/eleanorkonik/40+Slipbox/42+Zettels/African+nomads+and+villagers+have+symbiotic+relationships
