### ISSUE TITLE
Custom setting of words per page?

### ISSUE THREAD

**Issue by bonh** [isaaclyman/novel-word-count-obsidian#10]
Works great, thanks! 

It would be even better if I could change the number of [words per page](https://github.com/isaaclyman/novel-word-count-obsidian/blob/0b3a2fcaac56dc05af4d6dbf9c4de994f8a695c0/logic/file.ts#L99) through the interface.

**Comment by bonh** [comment]
Just noticed that you already discussed that option in #2. Perhaps if you don't want "users to feel like they need to worry about it" you could add a default value (300) and a help text specifying that this number "is an established standard in the publishing industry"?

**Comment by bonh** [comment]
Just noticed that you already discussed that option in #2. Perhaps if you don't want "users to feel like they need to worry about it" you could add a default value (300) and a help text specifying that this number "is an established standard in the publishing industry"?

**Comment by isaaclyman** [comment]
@bonh just curious, what’s your specific use case for changing that value? Since it’s come up again, it may be worth implementing.

**Comment by bonh** [comment]
For example, when writing grant applications(or paper) I take every headline from the grant template and create a new note in obsidian. Then I write away in obsidian (I hate writing in Word...). And now I use your plugin to get an approx. word count for each chapter (because they have page limits). But the proposal might be in size 11, double space or so. That's where I want to be able to set the words-per-page.

**Comment by isaaclyman** [comment]
Ah, well if it's for scholarly purposes I guess I can make something happen. Stay tuned.

**Comment by isaaclyman** [comment]
Fixed in 2.6.0.
