### ISSUE TITLE
FR: Customizable Timestamp Format

### ISSUE THREAD

**Issue by greetclammy** [isaaclyman/novel-word-count-obsidian#100]
**Problem**

The current timestamp format for "created date" and "last updated date" fields is too large and adds unnecessary clutter. It’s distracting, and there’s no way to customize it to make it fit better with the rest of my notes.

<img width="308" alt="image" src="https://github.com/user-attachments/assets/5271ebf5-145b-4490-bea4-2516bd9007e2">

**Idea**

Add an option to set custom formats for these timestamps using [Moment.js](https://momentjs.com/docs/#/displaying/format/). I’d like to use a more compact format that doesn’t take up as much space. If it’s possible, it’d be great to apply this customizable format to any frontmatter keys that are set as "date & time" types too. This would make things look cleaner and more consistent across my notes.

**Comment by isaaclyman** [comment]
The logs, like the developer console? Can you screenshot what you mean?

**Comment by joel72265** [comment]
I am not sure, if my request is the same as the original post.

e.g. For me the **Updated Date** shows 2024/11/05, would it be possible to customize the Update Date to show 05 Nov or 05 Nov 24 instead

**Comment by isaaclyman** [comment]
Got it, thanks.

Related: #70 and https://github.com/isaaclyman/novel-word-count-obsidian/issues/65#issuecomment-1830556858.

What I'm thinking at the moment is there could be a text box under "Advanced options" to let you put in a date string in [Moment.js format](https://momentjs.com/docs/#/displaying/format/). It would default to `YYYY/MM/DD`, which is what the app currently uses.

Would that meet your needs?

**Comment by greetclammy** [comment]
Yep, just what the doctored ordered!

For reference, here's *[Linter](https://obsidian.md/plugins?id=obsidian-linter)*:

<img width="779" alt="Screen Shot 2024-11-08 at 13 11 30" src="https://github.com/user-attachments/assets/684bb239-e788-4675-92ec-b4b67c826f32">

*[Update modified date](https://obsidian.md/plugins?id=frontmatter-modified-date)*:

<img width="785" alt="Screen Shot 2024-11-08 at 13 11 57" src="https://github.com/user-attachments/assets/5a2d9fef-262d-407d-ac0f-88a2eb80030d">
