### ISSUE TITLE
All plugin settings restore to default when disabling restricted mode

### ISSUE THREAD

**Issue by greetclammy** [isaaclyman/novel-word-count-obsidian#101]
**Description**

When I enable then disable restriced mode in Obsidian settings, all *Novel word count*'s settings restore to default. Having opened the plugin's `data.json` after performing each action, I have observed that the setting reset happens precisely at the moment I turn the restricted mode OFF. 

This affects *Novel word count* only, other community plugins are unaffected.

I have relaunched Obsidian and reinstalled the plugin but this didn't change anything.

**Device**

I'm only able to reproduce this on macOS 11.7.10 Big Sur:
```
SYSTEM INFO:
	Obsidian version: v1.7.5
	Installer version: v1.7.5
	Operating system: Darwin Kernel Version 20.6.0: Thu Jul  6 22:12:47 PDT 2023; root:xnu-7195.141.49.702.12~1/RELEASE_X86_64 20.6.0
	Login status: not logged in
	Language: en
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 34
	Plugins enabled: 1
		1: Novel word count v3.12.2

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

The theme is default.

It's super weird because I can't reproduce this in the sandbox vault or in the iOS app (1.7.5 also).

**Comment by isaaclyman** [comment]
Interesting...I can't guess why this would be happening. It seems like a fairly rare use case, but I'll leave the bug open in case you or someone else want to investigate before I get around to it.

**Comment by greetclammy** [comment]
If by a rare use case you're specifically referring to turning the restricted mode on then off, it's quite useful for when you have a bunch of plugins in use and something is broken, to isolate the issue--to see whether it's caused by a plugin or not. Also, if one wants to submit a bug report to the official forum, they must turn the restricted mode ON.

**Comment by isaaclyman** [comment]
I can't reproduce this on my vault. It may be caused by whatever plugin or system you're using for cloud sync.

**Comment by greetclammy** [comment]
How strange. This is still an issue in Obsidian 1.7.6. I use iCloud for syncing.

**Comment by greetclammy** [comment]
The issue seems to have resolved all on its own 🤷‍♂️

**Comment by greetclammy** [comment]
This ceased to be an issue for me.
