### ISSUE TITLE
for links it is not counting links like: [test](http://domain.org) 

### ISSUE THREAD

**Issue by ksdavidc** [isaaclyman/novel-word-count-obsidian#103]
**Description**

for links it is not counting links like: [test](http://domain.org) 
only links like [test](domain.org)

It seems to bomb on the colon : 

from Sandbox
<img width="762" alt="Screenshot 2024-11-17 at 8 42 05 PM" src="https://github.com/user-attachments/assets/fdb869b3-5300-4a51-9495-ceae4b5d6776">

SYSTEM INFO:
	Obsidian version: v1.7.6
	Installer version: v1.7.5
	Operating system: Darwin Kernel Version 23.6.0: Mon Jul 29 21:13:00 PDT 2024; root:xnu-10063.141.2~1/RELEASE_X86_64 23.6.0

**Comment by ksdavidc** [comment]
oops, wrong image. this shows it better.
<img width="750" alt="Screenshot 2024-11-17 at 8 42 35 PM" src="https://github.com/user-attachments/assets/db5799da-1791-41d5-a59a-f4ed9eb0ccc7">

**Comment by isaaclyman** [comment]
This plugin uses Obsidian's metadata to count links. Obsidian only counts internal links (i.e. to other notes), not external website links. See https://github.com/isaaclyman/novel-word-count-obsidian/issues/50#issuecomment-1679860720.
