### ISSUE TITLE
[FR] Option to Reset Track Session 

### ISSUE THREAD

**Issue by Drakemoor** [isaaclyman/novel-word-count-obsidian#105]
**Problem**
First, thank you for adding the Track Session option. It's super useful.

The issue is I rarely restart Obsidian, thus the Track Session counter to not reset. 

**Idea**

I would like an option to reset Track Session counter by using the Command palette. 

Thank you for your consideration and the great plugin.

**Comment by isaaclyman** [comment]
I believe there's already a command to Reanalyze the vault, which should reset the session.

**Comment by Drakemoor** [comment]
Thanks for the suggestion, although I was already aware of it. I thought it would take too much time to Reanalyze all the files in the Vault (my Vault has over 5000 notes).

I’ve tried Reanalyze, and it actually appears to be instantaneous. While it does what I need—resets the Track Session counter—I now have a different concern: does Reanalyze do anything at all?

How is it possible to count the words in over 5000 files in less than a second?

I’m just trying to understand.

Thank you.

**Comment by isaaclyman** [comment]
It does actually recount from zero, and it is very fast. I've done a fair amount of work on optimization, but in reality, string processing with simple regexes just isn't that CPU-intensive. Plus, Obsidian caches file contents for better performance.

I'm leaving this ticket open because I want to change the name of the command to "Reanalyze Vault / Reset Session" so it's clearer to other users.

**Comment by Drakemoor** [comment]
Thank you.

**Comment by Rudgas** [comment]
I wonder if making "track session" manual, might be even better, as startup/shutdown seems to vary so widely across the user-base. Adding the "reset" via commander-plugin to the ribbon would be no trouble at all.

**Comment by isaaclyman** [comment]
It might serve a wider customer base to have it be completely manual, but it would be more annoying to code. I'll change the name of the command in the next release but unless a ton of users request it, starting up Obsidian will also reset the session.

**Comment by isaaclyman** [comment]
The command is renamed in v4.2.0.
