### ISSUE TITLE
Current PageNo/TotalPages in Status bar

### ISSUE THREAD

**Issue by ShootingKing-AM** [isaaclyman/novel-word-count-obsidian#106]
**Problem**

Plugin shows kinda the page count in File/Folder level. Can it show the current page we are on in the Status bar too ? I understand its not in the scope of the plugin. But would be huge help. Since its hard to keep objective track of progress of reading.

Thanks in advance,

**Comment by isaaclyman** [comment]
Anything to do with the status bar would be a different plugin. Sorry, but I'm a solo maintainer and I'm not getting paid. I can't do everything.
