### ISSUE TITLE
Display Counts on Bookmarks Panel

### ISSUE THREAD

**Issue by ronrdev** [isaaclyman/novel-word-count-obsidian#108]
**Problem**

I like to use the bookmarks panel because it has custom sort and drag and drop making organizing scenes/chapters easy

**Idea**

Would be great to have word/page counts display on the bookmarks panel the same way as the files panel

**Comment by isaaclyman** [comment]
Line in the sand here, as this is an unpaid solo project: the plugin only affects the File Explorer pane. Everything else is out of scope.

Feel free to fork the repo, though.
