### ISSUE TITLE
Improve compatibility with file-explorer-note-count or other file explorer plugins

### ISSUE THREAD

**Issue by leoccyao** [isaaclyman/novel-word-count-obsidian#14]
**Problem**

When I first found this plugin, I was impressed by the amount of information it was able to place into a file explorer I would otherwise rarely keep open. The issue was, I was already using the [File Explorer Note Count Plugin](https://github.com/ozntel/file-explorer-note-count/), which also binds to and adds information the file explorer, and didn't want to give up folder note counts. For that reason, I put this plugin aside for a while.

More recently, I've came back to it, and recently found a workaround that allows for both functionalities. Noticing that both plugins try to bind to `.nav-files-container .nav-folder-title::after`, I instead edited `styles.css` to bind the `::after` to `.nav-folder-title-content` (which is a `<div>` inside `.nav-folder-title` that directly contains the text of the filename) and changed `item.titleEl.setAttribute` to `item.titleInnerEl.setAttribute`. This was causing word counts to display below file names; changing to `display: inline-block` made it work.

**Idea**

The most general way I can see to mitigate the issue of file explorer plugins conflicting, without specifically referencing other plugins, is to add a setting for choosing which `div` to add the pseudo-element to (for now, either `item.titleEl` or `item.titleInnerEl`). This could be labeled as an advanced setting for troubleshooting interactions with other plugins; it would also allow this plugin to stay compatible with future file explorer plugins that may try to also add pseudo-elements to various `div`s.

Though there are other possibilities:
- Allow for a new data source, number of files in folder (and recursing through subfolders), though this would increase complexity of display options (also see #15) and would also replicate some of the behavior of the other plugin (I personally would still use both at once, as note counts are displayed right aligned).
- Change the default behavior of this plugin to add the pseudo-element to `nav-folder-title-content`, though this might be a breaking change for some people who further choose to style their counts.
- Rewrite the plugin to use a method other than `::after`, though I am not sure how hard this is.

I've opened a similar issue in the other plugin: https://github.com/ozntel/file-explorer-note-count/issues/13, though it would be best if all file explorer plugins were able to support other ones as well.

Windows 10, Obsidian v1.0.0, Novel Word Count v2.7.1.

**Comment by isaaclyman** [comment]
I can add "file count" as a data display option, that won't be a problem.

As for compatibility with similar plugins, anything we could do there would make this plugin more brittle or harder to use, and ultimately would only accommodate a small number of conflicting plugins. At some point people have to make a choice. I'm willing to add new data types and make this plugin a one-stop shop for as many users as possible, but at some point "these plugins all want to display data in the exact same place" becomes an intractable problem no matter how you spin it.

**Comment by isaaclyman** [comment]
Note Count option added in v2.8.0.

**Comment by leoccyao** [comment]
Amazing! This is a small nitpick, but would it be possible to hide the "1 note"/"1n" next to individual files? It is a bit redundant to mark that every note is made up of one note.

**Comment by isaaclyman** [comment]
See #16.

**Comment by isaaclyman** [comment]
> would it be possible to hide the "1 note"/"1n" next to individual files?

In version 2.11.0, you can use the "Note count (folders only)" count option.
