### ISSUE TITLE
Other page count options?

### ISSUE THREAD

**Issue by feedhopper** [isaaclyman/novel-word-count-obsidian#17]
First of all: THANK you for the new update which solves the approach so much more elegant!
This is so much more useful now!!!

The categories below I left as "problem" though you could hardly call it that. It is just a deviation my home country decided on a long time ago.

**Problem**

Standard is 300 words per page. That is the international way. I live in Germany, where we have the "Normseite" way of things. 
https://de.wikipedia.org/wiki/Normseite#Nationale_Regelungen
Of course we had to do it a different way. And find a new means of working more
:(
It boils down to characters 1000-1800 characters excluding spaces. 

**Idea**

Is there any chance to implement an option for this?
:)

**Comment by isaaclyman** [comment]
Thanks for the suggestion. Fixed in 2.9.0. Please visit your plugin settings to select "Characters per page" as your page count method.

**Comment by feedhopper** [comment]
Oh WOW!
THANK YOU!!!!

I just saw this in the plugin update. Wonderful!
