### ISSUE TITLE
Support for CJK(Chinese, Japanese, Korean) characters please!

### ISSUE THREAD

**Issue by fenixfu** [isaaclyman/novel-word-count-obsidian#19]
**Problem**

I'm a user from china. This plugin is THE most convenient one to track how much words I've written. However, since it doesn't count CJK characters correctly, I've been tweaking the 'countWords' function with fragments ripped from Better Word Count. It works fine but I have to redo it every time there's an update. Could you please add CJK support (and possibly for other non-western languages)? Thanks a million!

**Comment by isaaclyman** [comment]
See #13. I want to implement something around this, I just haven't been able to figure out how. If Better Word Count does it well, though, that's very promising. Could you describe how you've been modifying the plugin to handle CJK? A link to the code file from Better Word Count you've been copying from would be really helpful as well.

As far as non-Western languages in general, I only speak Spanish and English and I don't know what I don't know. What would that look like, in your opinion?

**Comment by isaaclyman** [comment]
@fenixfu Bumping this so it doesn't get lost in your inbox—again, I'd like to build something here. A few pointers from you would be invaluable when you get the time.

**Comment by Wensupu-Yang** [comment]
I have the same needs. Bump on this @fenixfu @isaaclyman. 

Would love to see the support for CJK characters. 

Thanks a lot!

**Comment by isaaclyman** [comment]
@Wensupu-Yang Thanks for your input.

This is my top priority for the plugin right now, but I just don't have the expertise to make it happen. I speak only a few words of Chinese and no Japanese or Korean.

If someone could describe to me a simple way to count words in a character-based language I don't speak, I'd be happy to implement it.

**Comment by isaaclyman** [comment]
Version 2.12.0 includes a new "Word count method" setting that should correctly count files written in Chinese, Japanese, and Korean.
