### ISSUE TITLE
How do you calculate "page numbers"?

### ISSUE THREAD

**Issue by ReaderGuy42** [isaaclyman/novel-word-count-obsidian#2]
Really cool plugin! How do you calculate page numbers?
Thanks :)

**Comment by ReaderGuy42** [comment]
I just had a look through `main.js` and saw the thing:
`pageCount: Math.ceil(wordCount / 300)`

Would it be possible to add a setting for the plugin that asks the user the amount of words it should use per page? That'd be awesome, thanks!

**Comment by ReaderGuy42** [comment]
Another thing: I use a similar plugin that I adapted from this one: https://github.com/avr/obsidian-reading-time
which now shows me a page number in the status bar. However, I noticed that your plugin updates/refreshes the number better.

Would you mind telling me how you did that? So for example I'm writing in a note and it'll show "3 pages" and I add text, and by now it should be at "4 pages" but that doesn't appear until I change to another note and then back again. Whereas in your calculation next to the note title it refreshes the number more often.

Thanks :)

**Comment by isaaclyman** [comment]
Thanks for chiming in; I do appreciate the feedback.

I use the "modify" vault hook as follows: https://github.com/isaaclyman/novel-word-count-obsidian/blob/master/main.ts#L200. It gets a (debounced) callback every time a file is modified.

A custom setting for "words per page" is something I may be willing to consider later on, but 300 words per page is an established standard in the publishing industry and I don't want users to feel like they need to worry about it.
