### ISSUE TITLE
Support file types

### ISSUE THREAD

**Issue by juestchaos** [isaaclyman/novel-word-count-obsidian#20]
**Idea**

I hope to support file types. I can customize whether to count which file types.

**Comment by isaaclyman** [comment]
Related: #8.

If Obsidian reads something as a file, it will be counted. If you don't want it to be part of the folder-level count, put it in a different folder. Custom inclusion/exclusion settings sound like a never-ending source of issues to me (performance issues, compatibility with other plugins, constantly trying to outsmart the way Obsidian reads files, etc.).
