### ISSUE TITLE
Link, Attachments, & File Size Count

### ISSUE THREAD

**Issue by Mavdarez** [isaaclyman/novel-word-count-obsidian#22]
Would it be possible to show the 'links' or 'attachment' count like it does with word/page/etc. count? Would also be cool to see the file size count as well to know which folders/notes are what size.

**Comment by isaaclyman** [comment]
Re: links/attachments, what would that refer to specifically? I'm a bit of an Obsidian newbie, you might have to explain some terminology.

Re: File size, you mean like showing `1 MB` or `5 KB` on files and folders? That's probably doable.

**Comment by isaaclyman** [comment]
Closing until further information can be provided.

**Comment by isaaclyman** [comment]
v2.15.0 includes Link Count and Embed Count as options. File Size was also added in an earlier version. Letting you know in case these meet your needs.
