### ISSUE TITLE
Add ability to hide vault count

### ISSUE THREAD

**Issue by nimide** [isaaclyman/novel-word-count-obsidian#26]
**Problem**

What problem would your idea solve?
This would offer another way to customize for the user.
How do you currently manage this problem?
I don't.

**Idea**

Describe the feature you want to suggest.
I would like the ability to hide the vault count.

**Comment by isaaclyman** [comment]
As with #27, please add details on your use case and why this is valuable to you.

**Comment by nimide** [comment]
@isaaclyman, both of my requests would squarely fall into the quality of life category. These would help me clean up the user interface a little more. Presently, I only use your plugin for the number of notes in each folder. Since I already know what the number signifies, I have no need for the description, even when it is abbreviated. As for the vault count, I have a vault/home note that tells me the name of the vault, so I have hidden the vault name, but the vault count remained and is just an eyesore to me.

Thanks for all the work you've put into this plugin! It really is incredibly detailed, and although I don't use a fraction of the functionality at the moment, it's comforting knowing all of that is under the hood.

**Comment by isaaclyman** [comment]
See comment on the linked issue.

**Comment by isaaclyman** [comment]
This feature is implemented in v3.12.0.
