### ISSUE TITLE
Add ability to hide description.

### ISSUE THREAD

**Issue by nimide** [isaaclyman/novel-word-count-obsidian#27]
**Problem**

What problem would your idea solve?
This would offer another way to customize for the user.
How do you currently manage this problem?
I don't.

**Idea**

Describe the feature you want to suggest.
I would like the ability to hide the description after each number.

**Comment by isaaclyman** [comment]
Please add details on your use case and why this is valuable to you.

> This would offer another way to customize for the user.

That's an argument _against_ adding the feature. This is a word count plugin. The settings are already far more complex than any reasonable user would expect. I'd prefer to have fewer customizations, not more.

**Comment by isaaclyman** [comment]
There's another plugin that just shows note count without all the other bells and whistles: https://github.com/ozntel/file-explorer-note-count. Maybe that's more what you're looking for.

I'm closing this but might reconsider later on if other users request it as well.

**Comment by nimide** [comment]
Thank you for the consideration. I started out using the plugin you mentioned, but I one of the reasons I came over to this plugin is due to the lack of ongoing development for that one. There are a few issues (like not showing the numbers after restarting obsidian). Also, I think it had the same situation of showing the note number for the vault as a whole, but after reinstalling it, it looks like it is working as I would like (minus the issues that may never get fixed...).

**Comment by isaaclyman** [comment]
After several more requests, this feature has now been implemented in v3.0.0. Please update the plugin and check out the new "Use advanced formatting" toggle at the top of the plugin settings.

This was a big feature to implement and makes the plugin more difficult to maintain. If you find it useful, please consider [leaving me a tip](https://ko-fi.com/isaaclyman).
