### ISSUE TITLE
Hide count of notes for single notes

### ISSUE THREAD

**Issue by nimide** [isaaclyman/novel-word-count-obsidian#28]
**Problem**

What problem would your idea solve?
This would offer another way to customize for the user.
How do you currently manage this problem?
I don't.

**Idea**

Describe the feature you want to suggest.
I would like the ability to hide the number when the item in question is just a note.

**Comment by isaaclyman** [comment]
See #16. I'm avoiding doing this, though if people continue requesting it I may change my mind later on.

**Comment by isaaclyman** [comment]
Update: In version 2.11.0, you can use the "Note count (folders only)" count option.
