### ISSUE TITLE
Only show Note Count text for directories in file pane

### ISSUE THREAD

**Issue by ryanwwest** [isaaclyman/novel-word-count-obsidian#29]
When the data type to show is `Note Count`, individual notes in the file pane all display themselves as `1n`. I see the use for this for directories, but it seems unnecessary for single notes. I wonder if this should thus be displayed only on directories.

![image](https://user-images.githubusercontent.com/31378238/215301415-c1e7368c-5752-4bfa-88b0-1d1b3ce56877.png)

**Comment by isaaclyman** [comment]
See #16. I have concerns about this but more and more people are requesting it. I'll give it another think.

**Comment by ryanwwest** [comment]
Thanks. I've commented there to avoid duplicating features. Closing this duplicate issue but I appreciate you thinking about it more.

**Comment by isaaclyman** [comment]
Update: In version 2.11.0, you can use the "Note count (folders only)" count option.
