### ISSUE TITLE
Add chapter word count & show in Outliner

### ISSUE THREAD

**Issue by Mershainer** [isaaclyman/novel-word-count-obsidian#32]
**Problem**

I usually write novel in obsidian and
count words for every chapter. But the plugin don't have the function. What a pity.

**Idea**

Count words per chapter, which could be divided by H1 / H2 title. And the word number can show on the outline.

**Comment by isaaclyman** [comment]
You're writing an entire novel in a single note? I can't help you there. To me a novel is a vault and each chapter is its own note.

This plugin only alters the File Explorer pane, Outliner is out of scope.
