### ISSUE TITLE
Plugin broken in insider build v1.2.0

### ISSUE THREAD

**Issue by henrikfalk** [isaaclyman/novel-word-count-obsidian#33]
The plugin seems to load but seems not to work. Maybe because of the new "Bookmark" core plugin or some other changes?

I been using the "File Explorer Note Count" plugin for a long time which I found broken in the new insider build v1.2.0 and found a reference to your plugin when I reported the issue. Yours plugin looks like a better plugin :)

But it seems that yours plugin is broken as well?

![Screenshot_20230330_012612](https://user-images.githubusercontent.com/30142914/228690591-10dbedcc-d370-430a-8369-b41ae67feb0d.png)

**Comment by isaaclyman** [comment]
Fixed in 2.13.1.
