### ISSUE TITLE
Creating an API that would help get certain statistics from the vault

### ISSUE THREAD

**Issue by Amir1453** [isaaclyman/novel-word-count-obsidian#34]
**Problem**

Sometimes I need information regarding my vault, for example the total word count, or the total notes created or more specific information like the number of words in a folder.

**Idea**

Maybe some commands can be created that can be used in scripts, getting the total words, note counts and more information from vaults, specific folders and maybe even notes. 

By commands I mean an API, where I can import the commands into my javascript file and use the values in conjunction with something else. 

If this would require too much development time I understand, and I would be happy if you could tell me some alternatives.

**Comment by isaaclyman** [comment]
There are multiple options here.

- The plugin already shows word count and note count for every file, folder, and vault, so from one perspective it already does what you're asking.
- If you use bash, there are several commands like `wc` that can count words from the command line (see https://stackoverflow.com/a/35559868/4347245).
- All cached file counts are stored in a JSON file under `{my-vault}/.obsidian/plugins/novel-word-count-obsidian/data.json`. You could parse this file in a script and aggregate the results as needed.
- The word counting logic is really simple. You could borrow it from logic/file.ts in the repo and use it in your own scripts.
