### ISSUE TITLE
Count pages by number of lines

### ISSUE THREAD

**Issue by HanaNoAme** [isaaclyman/novel-word-count-obsidian#36]
I suggest adding a new way to count the number of pages: by number of text lines inside a note.

I sometimes use Obsidian to make lists that are much taller than they are wide, so the page count seems very off when a note containing a list that spans over multiple dozens of lines says it's only 1 page long.

**Comment by isaaclyman** [comment]
If there were a setting for this, it would apply to the entire vault. Do you have entire vaults made of lists with short lines?

I'm going to tag this and close it. If more people request it I'll revisit.
