### ISSUE TITLE
Page count method - Characters per page (including whitespaces)

### ISSUE THREAD

**Issue by carlgustavh** [isaaclyman/novel-word-count-obsidian#39]
**Problem**
In Danish colleges, a page is most commonly referred to as 2400 characters with whitespaces. No guideline is given for either words or characters without whitespaces. This means I have no accurate way of counting pages like I would in my essays. Currently I'm just using 2000 characters without whitespaces as a page which is ok but still a bit annoying,

**Idea**
Make a new option for page count method called "Characters per page (including whitespaces)" that would include whitespaces when counting characters for the page count.

**Comment by isaaclyman** [comment]
Yep, this is a reasonable request and easy to do. I'll implement it soon.

**Comment by isaaclyman** [comment]
Fixed in v2.16.0.

<img width="813" alt="Screenshot 2023-05-20 at 8 37 04 AM" src="https://github.com/isaaclyman/novel-word-count-obsidian/assets/9139369/3948519f-3e75-4d75-9631-366302988c41">

**Comment by carlgustavh** [comment]
Thank you so much
