### ISSUE TITLE
Performance: lags when typing

### ISSUE THREAD

**Issue by meskill** [isaaclyman/novel-word-count-obsidian#4]
Hello, thanks for the plugin.

But I have an issue with the plugin when I'm typing fast there are noticeable freezes for the obsidian interface.

For me, there is no need to update the info so often, so maybe a new setting option to update only on save will help.

**Comment by isaaclyman** [comment]
Hi @meskill, thanks for using my plugin. I'll need some more information to get to the bottom of this. 

- What device are you using the plugin on? How old is it?
- Do you have the latest version of Obsidian installed?
- How big is the note you're writing in? (How many words)
- Could you attach a screen capture video of the problem as it happens?

Obsidian debounces update hooks so it should only recalculate the number of words for the current note once every couple of seconds. It doesn't recalculate any notes other than the one you're currently writing in. However, I could imagine that on notebook-class computers or entry-level Android phones with very long notes, there could very well be some lag. If we can determine for sure what's going on in your case I'd be happy to explore options!

**Comment by meskill** [comment]
1. My specs are very decent, so it's not a problem with hardware
 ```
Processor	Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz   3.60 GHz
Installed RAM	32,0 GB73
System type	64-bit operating system, x64-based processor
 ```
 2. I have the latest public Obsidian version with a lot of other plugins :)
 3. I've tested in very small notes less than 50 words and lags are noticeable
 4. I've made some chrome profiling to show the issue
 
 Without the plugin, most of the tasks performed by obsidian are executed close to 100 ms or less:
![image](https://user-images.githubusercontent.com/8974488/160276093-94bb1c9a-b627-4da1-ad12-d4f6575c498c.png)

While with the plugin some tasks are executed up to 700 ms:
![image](https://user-images.githubusercontent.com/8974488/160276139-bc1d5bba-59e3-4c11-b7a0-ebfed1c5a330.png)

 Looking closer to the underperformed task there is lot happening in the plugin while typing:
![image](https://user-images.githubusercontent.com/8974488/160276228-c138bd83-b365-4a03-94b0-fdc8b5fb9a43.png)

You can find actual profile data [here - novel-word-count.zip](https://github.com/isaaclyman/novel-word-count-obsidian/files/8357308/novel-word-count.zip)

**Comment by isaaclyman** [comment]
Fascinating - thanks for replying with so much detail. Your computer is twice as fast as mine so you’re right, that’s definitely not the problem. The question remains, then, why I’m not seeing any lag on my five-year-old Windows computer. Possibilities that come to mind:

- Novel Word Count may be interacting in some way with one of your other plugins. If you temporarily disable all other community plugins (a real pain, I know) does the lag persist?
- Maybe there’s a bug causing recalculation of the entire vault every 2 seconds instead of just the current note. Case in point, that method you point to as taking 700ms+ shouldn’t be running *at all* while you’re typing. I’ll do some testing on my end today and try to determine why that might happen.

**Comment by meskill** [comment]
I've tried obsidian with only your plugin, and it works just fine, so this is definitely a conflict with some other plugin.

If I have some free time, I will try to figure out the conflicting plugin so do not waste your time.

**Comment by isaaclyman** [comment]
Thanks for checking that out. It might be helpful to look for plugins that do any of the following:

- Automatically rename files, including the one you're currently writing in
- Automatically rename any folder, or move files between folders
- Modify files other than the one you're working in (such as updating links)

If you're able to figure out which plugin is causing the conflict, I'll be happy to install it and see if there's a way to make them play nice.

**Comment by isaaclyman** [comment]
I'm closing this issue as I haven't heard anything in several weeks - @meskill, please feel free to open another issue if you discover which plugin is causing a conflict.

**Comment by isaaclyman** [comment]
@DevJake Thanks for your input. There's already a delay (debounce) built into the Obsidian hook for text changes in a file, so without a reproduction of the issue it's hard to know where more work is needed.

As for the ability to turn off automatic recounts, that seems worse than a real fix. It's something I'm willing to implement, but only if 1) I can be certain it fixes the problem and 2) I can't find another fix. So being able to reproduce the issue is a must-have.

Perhaps if you and @meskill can list out all the community extensions you have installed (copy out the contents of `.obsidian/community-plugins.json`) it would narrow things down? E.g. if there are extensions both of your vaults have, we could check those first.

**Comment by isaaclyman** [comment]
@DevJake thanks, hopefully @meskill will have a moment to share theirs as well.

If you get a few minutes later and want to pin it down on your own, I recommend a binary search to save time. I.e. disable half your plugins, see if the problem persists. Yes => narrow down to the enabled plugins, No => narrow down to disabled plugins. Then repeat. You've got 57 plugins, so it should take about 7 iterations to narrow it down to one plugin (assuming it's just one - to be fair, it could be several).

**Comment by meskill** [comment]
My list of plugins:

```
[
  "calendar",
  "cycle-through-panes",
  "cm-editor-syntax-highlight-obsidian",
  "obsidian-journey-plugin",
  "meld-encrypt",
  "smart-random-note",
  "review-obsidian",
  "obsidian-checklist-plugin",
  "slated-obsidian",
  "pane-relief",
  "tag-wrangler",
  "nldates-obsidian",
  "templater-obsidian",
  "table-editor-obsidian",
  "obsidian-admonition",
  "obsidian-kanban",
  "obsidian-metatable",
  "koncham-workspace",
  "sliding-panes-obsidian",
  "maximise-active-pane-obsidian",
  "obsidian-dictionary-plugin",
  "obsidian-zoom",
  "obsidian-collapse-all-plugin",
  "obsidian-vault-changelog",
  "quickadd",
  "copy-url-in-preview",
  "obsidian-cursor-location-plugin",
  "plugin-changelogs",
  "obsidian-recall",
  "customizable-sidebar",
  "alx-folder-note",
  "obsidian-hide-sidebars-when-narrow",
  "theme-picker",
  "tag-page-preview",
  "quick-explorer",
  "customjs",
  "hover-external-link",
  "drawio-obsidian",
  "customizable-menu",
  "workspaces-plus",
  "cmenu-plugin",
  "folder-note-core",
  "obsidian-prominent-starred-files",
  "obsidian-query-language",
  "obsidian-advanced-uri",
  "mysnippets-plugin",
  "obsidian-pipe-tricks",
  "obsidian-limelight",
  "obsidian-link-archive",
  "obsidian-image-caption",
  "customizable-page-header-buttons",
  "advanced-cursors",
  "obsidian-icon-folder",
  "obsidian-icon-shortcodes",
  "obsidian-regex-replace",
  "obsidian-memos",
  "obsidian-snippetor",
  "obsidian-image-toolkit",
  "obsidian-dynamic-highlights",
  "obsidian-style-settings",
  "obsidian-divide-and-conquer",
  "dataview",
  "settings-search",
  "tag-word-cloud",
  "obsidian-linter",
  "obsidian-better-command-palette",
  "persistent-graph",
  "big-calendar",
  "creases",
  "markdown-table-editor",
  "obsidian-remember-file-state",
  "obsidian-quiet-outline",
  "lapel",
  "obsidian-format-code",
  "obsidian-card-view-switcher-plugin",
  "obsidian-paste-image-rename",
  "macro-plugin",
  "obsidian-latex-suite",
  "tabout",
  "obsidian-scroll-offset",
  "typing-speed",
  "obsidian-banners",
  "obsidian-map-view",
  "hotkey-helper",
  "obsidian-git",
  "obsidian-sortable",
  "zoottelkeeper-obsidian-plugin",
  "periodic-notes",
  "obsidian-another-quick-switcher"
]
```

I've been trying to use [divide & conquer plugin](https://github.com/chrisgrieser/obsidian-divide-and-conquer) to find out the cause with binary search but didn't succeed as I'm not sure it works as intended.

And the list of intersected plugins with @DevJake is next:
```
[
    "calendar",
    "cycle-through-panes",
    "cm-editor-syntax-highlight-obsidian",
    "review-obsidian",
    "pane-relief",
    "tag-wrangler",
    "nldates-obsidian",
    "templater-obsidian",
    "table-editor-obsidian",
    "obsidian-admonition",
    "obsidian-kanban",
    "sliding-panes-obsidian",
    "obsidian-dictionary-plugin",
    "quickadd",
    "obsidian-image-caption",
    "dataview",
    "settings-search",
    "obsidian-banners",
    "obsidian-git"
]
```

**Comment by isaaclyman** [comment]
Thanks @meskill, I think there's enough info here to reopen the issue.

**Comment by isaaclyman** [comment]
@meskill @DevJake 
The list of intersecting plugins between you two looks pretty manageable. I'm going to do a bit of research and then go try to reproduce the issue.

A couple of things you two could do to help:

- If you have a vault that reproduces the problem and you're comfortable sharing it with me (publicly or privately), please either post it here or zip and email it to me (obsplugin@isaaclyman.com).
- If you disable all plugins _except_ the ones on the list of intersected plugins, does the problem still occur? It would be nice to narrow the issue down to those 19 plugins if possible.

Research notes follow.

**calendar**
*Visual, conflict unlikely*
Shows a calendar widget that links to notes by creation date.

**cycle-through-panes**
*Navigation, conflict unlikely*
Keyboard binding for switching tabs.

**cm-editor-syntax-highlight-obsidian**
*Content, **conflict likely***
Syntax highlighting in code blocks.

**review-obsidian**
*Scheduling, linking, **conflict likely***
Set a note to be linked from a future (or past) note.

**pane-relief**
*Navigation, conflict unlikely*
Nav history and hotkeys for navigating between panes.

**tag-wrangler**
*Linking, **conflict likely***
Extended tag functionality with "tag pages" that update themselves (?).

**nldates-obsidian**
*Contextual suggestions, conflict unlikely*
Inserts dates and note links based on natural language e.g. "next week".

**templater-obsidian**
*Dynamic code, conflict unlikely*
Tampermonkey for Obsidian.

**table-editor-obsidian**
*Content, conflict unlikely*
Easier markdown tables.

**obsidian-admonition**
*Content, conflict unlikely*
Material-design callout blocks.

**obsidian-kanban**
*Content and linking, **conflict likely***
Trello in Obsidian.

**sliding-panes-obsidian**
*Visual, conflict unlikely*
Split editor.

**obsidian-dictionary-plugin**
*Context, conflict unlikely*
Contextual dictionary/thesaurus.

**quickadd**
*Scripting and interop, **conflict likely***
Captures various types of content to a new note, includes scripting abilities.

**obsidian-image-caption**
*Content, conflict unlikely*
Add captions to images.

**dataview**
*Scripting, linking, **conflict very likely***
SQL-like inline queries that link notes as result sets.

**settings-search**
*Settings, conflict unlikely*
Adds a search bar to the settings window.

**obsidian-banners**
*Content, conflict unlikely*
Insert banner headers in documents.

**obsidian-git**
*Backup, conflict unlikely*
Automatically backs up/restores vault with Git.

So at this point my top suspects are:
- dataview
- quickadd
- obsidian-kanban
- tag-wrangler
- review-obsidian
- cm-editor-syntax-highlight-obsidian

**Comment by DevJake** [comment]
I have just tested all of the mutual plugins. I initially disabled the 'top suspects' list one by one, with no success. I then disabled the full list of 19 items one by one, again with no success. I then disabled the entire list, restarted Obsidian, then tried, and the lagging during typing issue persists. The issue only went after disabling the novel word count plugin. 

This would lead me to believe that it may not be a plugin conflict. As you noted, the plugin does not lag for your own vault. However, I am not sure of the size of your vault. My vault is (currently) 1,720 notes across 1,259 folders, mixed with 23,256 total files, totalling to 8.47GB. I have also included a line and file count for each programming-related file type within the vault. 

![image](https://user-images.githubusercontent.com/4295059/172725078-f1ae06a2-9b2a-4a05-b6e8-17ef82731391.png)

I believe it may simply be a product of the size of the vault and the amount of time it takes to check all of the files. Maybe some sort of caching would be of use? To only perform checks on files that have recently changed, not the entire vault. 

Let me know if there's any more testing I can do to help.

**Comment by isaaclyman** [comment]
@DevJake Thanks for taking the time to do that. In theory at least, the plugin already does what you're describing.

- If a file's contents change => only that file is re-counted
- If a file is moved to a different folder or renamed => the entire vault is re-counted

Earlier on in the conversation @meskill said:

> I've tried obsidian with only your plugin, and it works just fine, so this is definitely a conflict with some other plugin.

Are you saying you're getting lag when _all plugins_ except novel-word-count are disabled?

**Comment by DevJake** [comment]
> In theory at least, the plugin already does what you're describing.

That's good to hear. Equally, somewhat unfortunate to hear, since it means the issue stems from some other unknown reason... 

> Are you saying you're getting lag when all plugins except novel-word-count are disabled?

I get the lag when all of the 19 listed mutual plugins are disabled. I have not tried disabling _all_ of my plugins. Given that the plugins I did disable are all of the ones overlapping with meskill's list, then I very much doubt it would be the product of another plugin since there is no correlation there

**Comment by isaaclyman** [comment]
It's possible there are multiple plugins out there that independently have conflicting behavior with this one, but you're right, this does make that seem somewhat less likely.

I'm going to ship a "Debug mode" in the plugin that will output some information to the console. And then if you can take a moment to reproduce the issue, [open your Obsidian developer console](https://forum.obsidian.md/t/how-to-access-the-console/16703), and send me a screen/text capture of the output, hopefully that will give some indication of where the issue is coming from.

Hang tight in the meantime, I'll update here when I've shipped the update.

**Comment by DevJake** [comment]
Sounds like a great plan to me. Cheers 👏

**Comment by isaaclyman** [comment]
Well, I owe you two an apology. As soon as I implemented debug mode it became clear that a couple things weren't working the way I thought they were. In particular, a bug in the way I was using the cache was resulting in a complete recalculation of the vault on each file change.

Release #2.4.1 fixes these issues and a couple others. I expect there will be significant performance improvements on large vaults. Please try it out and let me know how it goes.

If there are more issues, the new debug mode provides plenty of detail in the dev console so we can track them down faster.

**Comment by DevJake** [comment]
Hey, no worries. I'm glad we managed to help you find the bug! I've now installed the new release and can confirm it has fixed all issues of typing lag. Brilliant work, thank you! 👏👏

**Comment by isaaclyman** [comment]
Great, I'm glad to hear it. @meskill feel free to report back as well, we can reopen the issue if you're still seeing lag.

**Comment by meskill** [comment]
works well, thank you for the fix
