### ISSUE TITLE
Add "alias(es)" option

### ISSUE THREAD

**Issue by pm64** [isaaclyman/novel-word-count-obsidian#40]
**Problem**

In addition to the useful info this plugin is already able to display, I'd love to have the option of displaying the note alias (if any)

**Idea**

I acknowledge that a feature like this begins to stray from the original purpose of this plugin. But I propose this feature anyway, since it would likely appeal to many users.

For my own purposes, an option to simply display the alias instead of the actual note title would work great (instead of adding an alias option as described above). If you'll entertain the idea of displaying the alias in some way, I'll let you decide which implementation is more appropriate.

**Comment by pm64** [comment]
Hey @isaaclyman, excited to check it out. I think your approach of providing a "first alias" option is the right move here, at least initially, as it should satisfy most use cases. Will 2.17.0 come through as a community plugin update, or should I use BRAT to update?

**Comment by isaaclyman** [comment]
Already available as a community update in Obsidian. You may have to click "Check for updates" in the community plugins screen.
