### ISSUE TITLE
ignore frontmatter

### ISSUE THREAD

**Issue by bblais** [isaaclyman/novel-word-count-obsidian#41]
Nice plugin -- however, it counts as words any frontmatter (the yaml at the start with the ---).   Since this is for counting words for writing, I don't think those should count or at least should have option to turn off counting yaml frontmatter.

thanks!

**Comment by isaaclyman** [comment]
Yeah, agreed. I've noticed that but was waiting to fix it until somebody complained.

Now you have, so I'll work on a fix.

**Comment by isaaclyman** [comment]
Fixed in v2.17.1.

**Comment by bblais** [comment]
Wow, that was fast.  😊   thanks!

Brian Blais

From: Isaac Lyman ***@***.***>
Date: Monday, June 12, 2023 at 16:43
To: isaaclyman/novel-word-count-obsidian ***@***.***>
Cc: Brian Blais ***@***.***>, Author ***@***.***>
Subject: Re: [isaaclyman/novel-word-count-obsidian] ignore frontmatter (Issue #41)

Yeah, agreed. I've noticed that but was waiting to fix it until somebody complained.

Now you have, so I'll work on a fix.
