### ISSUE TITLE
Novel Word Count not working with Obsidian 1.4.0

### ISSUE THREAD

**Issue by nomadphase** [isaaclyman/novel-word-count-obsidian#43]
**Description**

Since I have upgraded to Obsidian 1.4.0, Novel Word Count has ceased working. I think there may be a conflict with the properties function?

**Device**

I am using Obsidian on my Windows 10 desktop.

**Comment by isaaclyman** [comment]
Confirmed, there appears to have been some kind of breaking change. Looking into it.

**Comment by isaaclyman** [comment]
Root cause: https://github.com/obsidianmd/obsidian-api/issues/122

In the meantime, I'll push something to keep the plugin alive, but word counts may include frontmatter until Obsidian fixes their API.

**Comment by isaaclyman** [comment]
Fixed by 2.17.2, please update your plugin.
