### ISSUE TITLE
Ability to hide zero-values with a setting

### ISSUE THREAD

**Issue by 5HT2** [isaaclyman/novel-word-count-obsidian#49]
**Problem**

Seeing "0 links | 0 embeds" is incredibly visually busy, and it makes it hard to pick out notes which have many links / rich content, as I use it to later review notes for more content and reading to explore.

**Idea**

An opt-in setting to hide data types that have a zero-value.

**Comment by isaaclyman** [comment]
There's a precedent for hiding uninformative data, since aliases won't show if a note has no aliases. I'd prefer not to add another setting if possible, so I'm going to hide those by default on the next release and see who complains.

**Comment by isaaclyman** [comment]
Fixed in v2.21.4. Please update your plugin and let me know if any issues remain.
