### ISSUE TITLE
Show also character count

### ISSUE THREAD

**Issue by Nachtstreife** [isaaclyman/novel-word-count-obsidian#5]
Hi, 

the Novel Word Count offers an excellent feature and this addon for Obsidian would be exactly what I am currently looking for if another variable could be used: For me it is more important to know the count of characters instead of the word count as the texts I write typically have a limit based on the number of characters. If this could be shown as an alternative selection, it would provide me with the perfect overview for my use cases.

**Comment by isaaclyman** [comment]
This is a reasonable request and easy to add. One moment please.

**Comment by isaaclyman** [comment]
Release [2.3.0](https://github.com/isaaclyman/novel-word-count-obsidian/releases/tag/2.3.0) includes Character Count as an option. Please update to the latest version of the plugin and let me know if you have any trouble.

**Comment by Nachtstreife** [comment]
Wow, thank you very much for this fast implementation. This help is much appreciated!
