### ISSUE TITLE
Links are not being counted in folders

### ISSUE THREAD

**Issue by 5HT2** [isaaclyman/novel-word-count-obsidian#50]
**Description**

Links are not being counted for most files / folders? I'm not really sure why it shows links for some files and why it doesn't for others, when the majority of these files do contain links.
![](https://frogg.ie/3Gx)

Examples of links I have tried:
- `https://github.com/isaaclyman/novel-word-count-obsidian`
- `obsidian://show-plugin?id=novel-word-count`
- `[🔗](https://github.com/isaaclyman/novel-word-count-obsidian)`
- `[🔗](obsidian://show-plugin?id=novel-word-count)`

**Device**

Linux, Obsidian v1.3.7

**Comment by isaaclyman** [comment]
Links are counted by Obsidian itself, not this plugin—I'm just using their count from the note metadata. It appears they only count internal links, e.g. `[[MyOtherNote]]`.

**Comment by isaaclyman** [comment]
There was a bug preventing link counts from propagating up to folders. It's fixed in v2.21.4.
