### ISSUE TITLE
[Feature Req] Enable wc on some folders only

### ISSUE THREAD

**Issue by championswimmer** [isaaclyman/novel-word-count-obsidian#52]
**Problem**

I use Obsidian for other things as well (not just novel writing) - so I do not need counts on all folders

**Idea**

Enable word counts on only some folders.

**Comment by isaaclyman** [comment]
A "per-folder" option would add a lot of complexity to the settings. The official solution for this is "vaults are free, so put your novels and your other stuff in different vaults."

**Comment by isaaclyman** [comment]
@championswimmer As of v3.3.1, there's an "Include file/folder names" setting you can use to only count the folders/notes you want.
