### ISSUE TITLE
[Feature request] Only show file counts on enabled extensions

### ISSUE THREAD

**Issue by RLGingerBiscuit** [isaaclyman/novel-word-count-obsidian#57]
**Problem**

I believe that if a file is not in the allowed extensions list, it shouldn't show the word count in the file explorer, as it will always show '0 words'.

**Idea**

The simple solution (as implemented in in #56), simply disables all information if the extension isn't in the whitelist (whilst not affecting folders in any way). It could possibly be made a setting, and perhaps file size and dates should be allowed to be shown.

**Comment by isaaclyman** [comment]
I think the lowest-friction solution here is to hide "conditional" counts such as character/word/page on files that shouldn't be counted and on folders that _only_ contain such files; and to always show "unconditional" counts such as created date and file size. I've pushed a commit to that effect; thank you very much for your issue and PR.
