### ISSUE TITLE
A question about "Note Count" and "png, jpg" type files

### ISSUE THREAD

**Issue by xhuajin** [isaaclyman/novel-word-count-obsidian#58]
I just realized that files like png, jpg are also counted under Note Count, and happened to find out that an update three days ago had something to do with this issue. I updated the plugin to test it again, but realized that the update just hid the counting of these files, they are still counted in Note Count. For example, I have a folder with 10 files, but 20 images. The Note Count of the folder shows 30n. This is obviously not the result that needs to be counted. Would it be possible to add an option to disable the counting of this type of files? Thank you very much for seeing my problem.

**Comment by isaaclyman** [comment]
I think you're right about this. Update incoming.

**Comment by isaaclyman** [comment]
Fixed in v2.23.6.
