### ISSUE TITLE
[feature request] word counter for new window (pop-up)

### ISSUE THREAD

**Issue by somehowko** [isaaclyman/novel-word-count-obsidian#59]
**Problem**

Sorry for the confusion on the previous request. 

By new window I meant the poped up tap opened when the curnrent tap is "moved to new window".

The option is available by right clicking a tap or command ("move current  tap to new window")

![image](https://github.com/isaaclyman/novel-word-count-obsidian/assets/87083217/afb63094-c134-4426-8594-b1d722130cbd)

When opened, the new window doesn't have any side bar or status bar, and none of them can be toggled. 
(just like quick reference on scrivener, it is just a pop up editor.) 

The problem is that none of counter works on new window as status bar and side bar doesn't exist on the new window.

**Idea**

If the tap title includes word count, or if there is anyway to bring the status bar to the poped up window, the problem would be solved.

I don't know if this is enough information to begin with, but hope this could be acheieved with the plug-in.

**Comment by somehowko** [comment]
Oh, I read the final reply just now.

If this is not possible, or the plugin is exclusively for the explorer pannel, please close the request. 
Thanks.

**Comment by isaaclyman** [comment]
Duplicates #53.

It sounds like this should be filed as a bug for the Word Count core plugin. This plugin only shows data in the File Explorer pane.
