### ISSUE TITLE
[Feature request] Characters counting without spaces 

### ISSUE THREAD

**Issue by mossbergmaverick** [isaaclyman/novel-word-count-obsidian#60]
Any counter for Obsidian calculates all characters in document, including spaces

Is it possible to add option to count only characters but ignore spaces? Google Docs gives this ability, will be cool if this appears in your extension.

**Comment by isaaclyman** [comment]
Yes, it could be done. What's your use case for this feature? If it's for German page count (Normseite), you can set the Page Count Method to "Characters per page" and toggle off "Include whitespace characters in page count".

**Comment by mossbergmaverick** [comment]
In the Czech Republic, Slovenia, and Poland, it's common to gauge the length of a text by counting characters without spaces, rather than by words, particularly in translation. This can pose a challenge in adhering to character limits, often leading to exceedances.

**Comment by isaaclyman** [comment]
Understood. Language compatibility is a priority for me, so I'll work on this as soon as I can.

**Comment by isaaclyman** [comment]
Fixed in v2.24.0.
