### ISSUE TITLE
List item prefixes are counted as words

### ISSUE THREAD

**Issue by redactedscribe** [isaaclyman/novel-word-count-obsidian#62]
**Description**

7 words:

```markdown
- 1
- 2
- 3
- 
```

Same goes for `*`- and `+`-prefixed lists. The core plugin "Word count" also has this issue, but only for `-`-prefixed lists (which will hopefully be fixed).

**Device**

Windows.

I originally posted this [here](https://github.com/lukeleppan/better-word-count/issues/107) by accident. I was attempting to see why word counts were not the same and got the repos confused.

Thanks.

**Edit:** Apparently this is [a known special case](https://forum.obsidian.md/t/word-count-based-on-preview-rendered-text-not-editor-text/4758).

**Comment by isaaclyman** [comment]
Novel Word Count defines a "word" as any sequence of one or more non-whitespace characters.

I'm reluctant to change this for two reasons:

- People have differing opinions of what should be considered a word.
- _Software_ has differing opinions of what should be considered a word. If you're writing in Obsidian with the intent to paste your content into another app or a form, it would be detrimental to exclude things (especially things visible in Reading Mode) that the other software would include.
- NWC's performance has been tuned and re-tuned and at present is pretty fast (can count 4.8 million words in less than a second on my MacBook Air). If I go down the path of letting people fight out more and more specific inclusions and exclusions to the "word" regex, performance will degrade, especially on large vaults.

I'm closing this for now, but if more users start requesting it, I can reconsider.

**Comment by isaaclyman** [comment]
@redactedscribe This should be fixed now (v3.4.0).
