### ISSUE TITLE
File Size data type to use accurate unit symbols

### ISSUE THREAD

**Issue by redactedscribe** [isaaclyman/novel-word-count-obsidian#63]
**Description**

_Without_ abbreviations enabled a 10 kilobyte file is displayed as "10 KB" when [it should be "10 kB"](https://en.wikipedia.org/wiki/Kilobyte) when using the SI definition.

_With_ abbreviations enabled, arguably incorrectly displayed as "10kb" (i.e. kilo*bits*).

**Device**

Windows

**Comment by isaaclyman** [comment]
Yeah, I figured I was butchering the SI units. A person would have to be pretty pedantic to think I was measuring file size in kilobits, but I'm all for accuracy. Stay tuned.

**Comment by isaaclyman** [comment]
Fixed in v2.25.1.

**Comment by redactedscribe** [comment]
Pedantic? I don't know who you're taking about.

Thanks!
