### ISSUE TITLE
Treat folders and files separately

### ISSUE THREAD

**Issue by redactedscribe** [isaaclyman/novel-word-count-obsidian#64]
**Problem**

It doesn't make sense to display the Note Count data type on notes (each is "1 note").

**Idea**

If we could define the three data types for both notes _and_ folders, we could set up folders to display the note count, and notes with whatever makes sense for them.

Thanks.

**Comment by isaaclyman** [comment]
This already exists. Untoggle "show same data on folders."

**Comment by redactedscribe** [comment]
Right. My bad! Just what I was looking for.
