### ISSUE TITLE
Inaccurate counting of mixed Chinese and English

### ISSUE THREAD

**Issue by alchemy-lee** [isaaclyman/novel-word-count-obsidian#71]
Hi, when I write mixed Chinese and English in the note, the counting of novel-word-count is not accurate. For example:

```
hello 世界世界世界 hello hello
```

obsidian status bar:
<img width="243" alt="image" src="https://github.com/isaaclyman/novel-word-count-obsidian/assets/23042232/6d2b76c6-e116-4338-bdbc-26ef2fb8f3ba">

novel-word-count:
<img width="206" alt="image" src="https://github.com/isaaclyman/novel-word-count-obsidian/assets/23042232/35a29897-07c8-4e88-a43b-71eefa470419">

The actual word count is 9 words, but novel-word-count report only 6.

**Comment by isaaclyman** [comment]
For performance reasons, I've been counting each note as space-delimited _or_ CJK, rather than trying to incorporate both into one RegEx. This is the first complaint I've had, but it doesn't look like it would be too difficult to combine them and possibly remove the setting to switch between them. I'll try it and see how it affects performance.

**Comment by isaaclyman** [comment]
Please note, however, that the word count will likely never match up between Obsidian's status bar and Novel Word Count. See #38.

**Comment by isaaclyman** [comment]
After some research, I'm going to say no to this one for now. Counts for mixed-language notes would require a much more advanced RegEx, versus the simple, fast, and easily understandable ones I use now. You'll have to decide which counting method you prefer.

At some point I may experiment with a custom lexer and see if it can keep up with `String.prototype.match` while also allowing higher logic than a RegEx, but no promises.

**Comment by isaaclyman** [comment]
This has been fixed in v3.4.0. Mixed-language notes should now be counted correctly.
