### ISSUE TITLE
Ability to exclude code blocks from word count

### ISSUE THREAD

**Issue by Mestru** [isaaclyman/novel-word-count-obsidian#76]
**Problem**
I'm (and I assume some people are also) using a lot of ``` code blocks to write dataview and dataviewjs scripts to visualise things within our obsidian notes. Currently Novel word count is counting code written within those code blocks as words. I acknowledge that it might be useful for a one-off note to track amount of words written within code blocks but for scenarios where I put a code block in my template which I then reuse over multiple notes, it artificially blows up the word count which is not ideal.

**Idea**
It would be nice to either offer an option to exclude code blocks from word counting OR offer a customizable solution that lets users define a prefix/suffix/something that will indicate the following to not be tracked.

Thanks for the work you did in creating the plugin and have a nice day regardless of what you think of this suggestion :)

**Comment by isaaclyman** [comment]
See also #74.

**Comment by isaaclyman** [comment]
Closing in favor of the other issue.
