### ISSUE TITLE
DevTools failed to load source map System error: net::ERR_FILE_NOT_FOUND

### ISSUE THREAD

**Issue by vtulus** [isaaclyman/novel-word-count-obsidian#77]
**Description**

I see the following message in the Developer Console at startup:
`DevTools failed to load source map: Could not load content for app://obsidian.md/styles.css.map: System error: net::ERR_FILE_NOT_FOUND`  
I believe this started after the latest update, v3.3.3

**Device**
Windows device

**Comment by isaaclyman** [comment]
@vtulus Can you verify that this only happens when the plugin is enabled?

**Comment by vtulus** [comment]
> @vtulus Can you verify that this only happens when the plugin is enabled?

Yes, it does. 
I went over all the plugins and it only happens when this plugin is enabled 😊

**Comment by isaaclyman** [comment]
Thanks, turned out to be a quick fix.

Fixed in v3.3.4.
