### ISSUE TITLE
Exclude file/folder names

### ISSUE THREAD

**Issue by Drakemoor** [isaaclyman/novel-word-count-obsidian#81]
**Problem**
I would like to be able to exclude specific files, folders, or both from being counted. 

I have a big vault organized in folders. I also use the `Folder Notes` plugin. In those notes, I store info I don't want to be counted because they skew the numbers of the containing folders. 

I use Obsidian for long-form writing, separating each project into its own folder. Some projects contain over 50 folders, and some of the folder notes contain a significant amount of words. That changes the number of the overall project word count, which I view as a guide to the project's progress. 

**Idea**
I  would like to have a field like this:
![image](https://github.com/isaaclyman/novel-word-count-obsidian/assets/93224920/fee92353-d58f-48c9-ad6d-300819c55e7e)

in the options, so I can easily **`EXCLUDE`** file/folder names.

Thank you for your consideration.

**Comment by isaaclyman** [comment]
There are three ways to exclude notes:

- Using the `#exclude-from-word-count` tag in the note Properties.
- Using `wordcount: false` in the Properties.
- Using the "Include file/folder names" setting.

See the README for more details on any of these.

**Comment by Drakemoor** [comment]
Thank you for getting back to me so quickly. 

I've read the README and know about the possibility of using a tag or property. Unfortunately, this doesn't solve my problem since I have to add it to hundreds of preexisting `Folder Notes`. 

I also know about the "Include file/folder names" option, but I couldn't make it work. I've tried variants of this regex:
```regex
(?!__aboutFolder_.*)
```
to no avail.

If you know any way I could achieve what I want, please, help me. 
Thank you.

**Comment by isaaclyman** [comment]
Ah, sorry for misunderstanding. RegEx isn't an option in that setting, it's a plaintext match. Have you tried setting it to `__aboutFolder_`?

**Comment by Drakemoor** [comment]
Thank you, for your help.

**Comment by isaaclyman** [comment]
@Drakemoor Fixed in v3.8.0. The "Include file/folder names" setting has been updated so any term starting with `!` will be excluded instead of included. Try setting it to `!__aboutFolder_` and let me know if it doesn't work.

**Comment by Drakemoor** [comment]
Thank you for the time you put it! 🙇🏻‍♂️

I tested it, and it works well. I appreciate it.
