### ISSUE TITLE
Add feature to disable caching?

### ISSUE THREAD

**Issue by Cyerdous** [isaaclyman/novel-word-count-obsidian#83]
**Problem**

So I use git to backup my vault and access it across different devices, and when I don't keep everything perfectly synced the data.json for novel-word-count gives me merge conflicts, I would add it to my .gitignore however I want to keep my settings synced across devices when I can.

**Idea**

Add a feature to disable caching of word counts in data.json. Its fine if it needs to rebuild word counts on startup, that's something I can tolerate. It might be possible to cache word counts to a different file than the settings, that would also solve my problem as that could be added to .gitignore without risking mismatched settings

Thank you!

**Comment by isaaclyman** [comment]
I'm reluctant to add yet another setting if this is an uncommon use case. I'll leave the issue open for a while and see if any other users have feedback.

As for moving the data to another file, that's not directly supported by the Obsidian API, and some users may have processes or scripts that read `data.json` to get word counts.

Do you change your settings often? It might be easy enough to gitignore the `data.json` for this plugin specifically, then update a setting or two on each device as needed.

**Comment by Cyerdous** [comment]
Honestly I'm a fiddler, but I think I have it tuned in for now. So I'll probably just add it to gitignore for now and try and sync it on occasion, thank you though.

**Comment by isaaclyman** [comment]
v5.0.0 of the plugin, just released, does not store count data in `data.json` by default. This may help address the issue. Feel free to update and let me know if you see any further issues.
