### ISSUE TITLE
Full Novel/Vault Word Count Missing Following Obsidian Update

### ISSUE THREAD

**Issue by StGareth** [isaaclyman/novel-word-count-obsidian#87]
**Problem**

Following the latest Obsidian update where the vault switcher was added, the app no longer displays the vault name at the top of the file tree, thus you can't see the full vault word count:
![image](https://github.com/isaaclyman/novel-word-count-obsidian/assets/101667864/6ade4e7b-446a-4c51-9f39-fbe3c31fc49c)
You can get around this by adding a new top level folder, but not ideal since it adds another level of link.

**Idea**

Either show the vault name and wordcount as was previously just through this plugin, or show the wordcount next where the vault name is currently displayed at the bottom:
![image](https://github.com/isaaclyman/novel-word-count-obsidian/assets/101667864/0a9dd3b1-0696-4b97-8482-abb892823feb)

**Comment by isaaclyman** [comment]
Thanks for the heads up, I'll look into it.

**Comment by isaaclyman** [comment]
<img width="373" alt="Screenshot 2024-06-09 at 10 56 08 AM" src="https://github.com/isaaclyman/novel-word-count-obsidian/assets/9139369/d35ace0d-5248-42d6-923d-983346d8c9dd">

It seems like the best place for it is at the top, right underneath the header buttons. That way there's plenty of space for long counts.

**Comment by isaaclyman** [comment]
Fixed in 3.10.0, now available.

**Comment by isaaclyman** [comment]
3.10.2 fixes some styling issues with the vault count on desktop on mobile.
