### ISSUE TITLE
Customizable Count for Headings / Sections

### ISSUE THREAD

**Issue by chrisspiegl** [isaaclyman/novel-word-count-obsidian#88]
**Problem**

I really like the customization options of this plugin, especially the many options to count stuff (words, characters, reading time).

But I’d love to see this based on chapters in my markdown document (aka next to the headings for that section).

**Idea**

The idea would be to display up to 3 counters next to a section heading in the document. Similar to the following design:

<img width="350" alt="image" src="https://github.com/isaaclyman/novel-word-count-obsidian/assets/1096384/1bfcbc4a-b9db-4e0a-9a4c-a6f0537e9c0a">

Then make this customizable the same way the file explorer word count can be selected with up to three counters.

Personally, I think this would be a great addition to this plugin for those of us who want to write multiple chapters in one document.

Thank you for your consideration.

**Comment by isaaclyman** [comment]
To keep this plugin maintainable as a solo project, I've drawn two lines in the sand:

1. No editing the user's files.
2. Nothing outside the File Explorer pane. 

I'm going to stick with those unless this plugin gets a lot more profitable.

**Comment by chrisspiegl** [comment]
Understood. Thank you for the clarification 👍.
