### ISSUE TITLE
option to turn off for folders instead of 'none'

### ISSUE THREAD

**Issue by sikaios** [isaaclyman/novel-word-count-obsidian#92]
**Problem**

Even if I set the folders to show none, it interferes with similar plugins such as [file explorer note count](https://github.com/ozntel/file-explorer-note-count). Also, even with 'none' toggled, it shortens my folder names from, for example, "Evergreen" to "Eve..." unless I set it to inline.

**Idea**
Is there a way to make the settings able for the folders be completely turned off?

**Comment by isaaclyman** [comment]
Can I ask why you would use Novel Word Count and File Explorer Note Count together? I believe this plugin covers all the functionality of the other.

**Comment by hanaTsuk1** [comment]
I do the same thing. Maybe we all don't want to see the total count displayed at the top of the workspace. 🤣

**Comment by isaaclyman** [comment]
I'm not able to reproduce this one. Maybe some more details and screenshots would help?

Compatibility with every other plugin is not a goal of this plugin, so if you want to pursue this, please help me reproduce the error without any other plugins installed.
