### ISSUE TITLE
Adding conditional styling to label based on value.

### ISSUE THREAD

**Issue by KrazyManJ** [isaaclyman/novel-word-count-obsidian#93]
**Problem**

I would like to apply zettelkasten to my vault and key thing is to have notes of maximum size 150 words each.

**Idea**

I would like to add style rules, for example if number of words in note is higher than 150, it will color the size label to the red. It can be done with CSS classes (add CSS class when it meets conditions) and style it via snippets.

**Inspiration**

This feature is inspired by [kanban plugin](https://github.com/mgmeyers/obsidian-kanban) when date and time is colored based on value - useful for deadlines warning.

**Comment by isaaclyman** [comment]
If you're looking for a visual indicator when a note has reached/surpassed a certain word count, the [Writing Goals](https://github.com/lynchjames/obsidian-writing-goals) plugin may be a good fit.

I don't think it makes sense for this plugin.

**Comment by KrazyManJ** [comment]
Thank you for your suggestion, I will take a look at that. I fully understand why it does not make sense to do, when it's in another plugin already implemented.

Thank you for your response, love your plugin btw <3
