### ISSUE TITLE
Display a custom key in the front matter block

### ISSUE THREAD

**Issue by hanaTsuk1** [isaaclyman/novel-word-count-obsidian#94]
**Problem**

I manage time data in the front matter block, and the reason for doing so can be seen in this [post](https://forum.obsidian.md/t/handle-file-creation-date-modified-date-internally-dont-use-the-filesystem-info/26148)

I hope to provide another way to display the created time and updated time

**Idea**

Provide an option to choose data from front matter, and then provide an input to fill in the specific key

**Comment by isaaclyman** [comment]
Sorry for the late response. I would accept a PR on this, but I'm not in a position to write it myself anytime soon.

**Comment by hanaTsuk1** [comment]
Got it, thank you for considering this request

**Comment by hanaTsuk1** [comment]
I have implemented this feature. If you think it is OK, I will submit a PR.

https://github.com/hanaTsuk1/novel-word-count-obsidian/tree/feat/custom-key

**Comment by isaaclyman** [comment]
The code looks great. Really solid work. I have a few small suggestions and want to do some testing, but go ahead and PR and I'll add a few comments.

**Comment by hanaTsuk1** [comment]
I have created it, please check

**Comment by isaaclyman** [comment]
PR merged and released. Thanks for your help!

**Comment by hanaTsuk1** [comment]
🥳

**Comment by hanaTsuk1** [comment]
I tried the latest version and found that after turning on 'Use advanced formatting', the file tree displayed 'undefined'🧐. I looked for the reason and found that 'COUNT_TYPE-DEFAULT_SHOR_SUFFIXES' did not set the initial value for' FrontmatterKey '. I missed this point and left a message here for you to see

https://github.com/isaaclyman/novel-word-count-obsidian/blob/master/logic/settings.ts#L88

`
[CountType.FrontmatterKey]: "",
`

![oPVMV8tggT](https://github.com/user-attachments/assets/f87afffc-0113-499d-915d-d2c4a7b3a1d9)

**Comment by isaaclyman** [comment]
Good catch. Fixed in v3.11.1.
