### ISSUE TITLE
Session Based word count (formerly daily)

### ISSUE THREAD

**Issue by Rudgas** [isaaclyman/novel-word-count-obsidian#96]
**Problem**

Hey, would you consider adding a daily word count? I've tried Daily Statistics, Daily Stats and Better Word count which all report different numbers, up to ~10% off from what your plugin is reporting. Also, they don't include the Canvas in the daily word count.

**Idea**

A status Bar "n words today" counter. I like the implementation of better word count to allow a custom pre/suffix, but don't think it's really necessary. Cherry on top is logging and visualization :-)

Thanks for the effort to make the plugin in the first place!

**Comment by isaaclyman** [comment]
Take a look at [Writing Goals](https://obsidian.md/plugins?id=writing-goals), that's typically what I recommend for this kind of thing.

Exact parity with Obsidian's own word count, or with other plugins, isn't a goal of this plugin. There isn't an established "right way" to count words, so of the options available, I picked one that is easy to understand and maintain. See #38 for more details.

**Comment by Rudgas** [comment]
Unfortnately Writing Goals doesn't include a daily word count (without setting a daily goal).

I didn't mean for you to adjust your word count method to available solutions, rather displaying the daily word count based on the same method the word count is already shown for all the folders. (As that is not available).

**Comment by isaaclyman** [comment]
I see. Thanks for clarifying.

Time-based counts would be new to this plugin, and there have been enough bugs around timezones and formats in the Created/Updated Date data types that I'm reluctant to take on the complexity. Still, I can wait and see if more requests come through; I might consider it.

As for implementation, the Status Bar is strictly off limits to this plugin. Novel Word Count only touches the file explorer. So if it ever did get implemented, it would be as a data type there.

**Comment by Rudgas** [comment]
Thanks for the response! Yeah mucking around with timezones is not particularly fun.

Just thinking aloud, I wonder if it would make it a bit simpler if the user can define the timezone (to avoid trouble with the fetched locale) and the preferred hour of "reset". This should be relatively ok to translate to unixtime + 24*60*60 as the windows for counting.
Watching the root-folder wordcount for changes would give the difference in counted words without having to interact with the database and looking through "Last-modified" dates.
Super-simple Version would be just use word-count on obsidian startup and reset on close.
Giving the root-folder it's own configuration would look quite pretty I think. Can imagine there would be some interest to have a different setting from folders.

Anyway, have a coffee on me for the excellent plugin so far :-)

Cheers!

**Comment by isaaclyman** [comment]
Hey, thank you. That's so kind.

"Words since startup" is a good idea, if it would meet your needs. I just want to reiterate that it would only appear in the File Explorer pane, not the status bar.

**Comment by Rudgas** [comment]
![obsidian_screenshot](https://github.com/user-attachments/assets/fb6760cc-7df4-4e87-81d6-28244b3e5280)

"Words since startup" would totally work for me! Thanks for considering it!

I get why you would want to keep changes in the explorer view only.

Aesthetically I think it would be best to go in the green area. If "Words since startup" becomes a "data type to show", adding a root-folder setting would be nice, since the file-view might get quite cluttered if it is added in line to each file/folder.

**Comment by isaaclyman** [comment]
There have been a number of requests to include/exclude the root folder. I'll start with that as soon as I get some time.

**Comment by isaaclyman** [comment]
Root counts can be set independently from folder/file counts as of v3.12.0.

"Words since startup," I've realized, is likely larger than a single count type. Sooner or later someone's going to ask for "pages since startup" and "characters since startup." I need to think this through and come up with a more holistic solution, preferably one that doesn't make the settings _even more_ intimidating for a new user.

In spite of my efforts, it's beginning to look like an airplane cockpit.

**Comment by Drakemoor** [comment]
So, what's the name of the option for the daily word count? I looked but I could not find how to show it.

**Comment by isaaclyman** [comment]
@Drakemoor Check the thread. It doesn't exist yet, which is why the issue is still open.

**Comment by Rudgas** [comment]
"Track Session" could be a 1st/2nd/3rd datatype which then inserts a dropdown menu to select words/chars/pages etc. (similiar how the 'suffix' line only appears on options where it's available).
Personally I like the design with the "advanced" options toggle to hide the fiddly bits. And likewise the expanding menu for daily words/chars/pages etc. will only appear if selected.

**Comment by isaaclyman** [comment]
I like that idea a lot. Especially because it doesn't complicate the existing, most popular count types. It does add a second layer of complexity, but that's probably unavoidable.

I'll hopefully get to this sometime in November.

**Comment by Rudgas** [comment]
Glad to help a little bit.

I've thought about the idea a bit longer, and come to realise that I like the session-based word count a lot more than a daily one. I've changed the title accordingly.

**Comment by isaaclyman** [comment]
The "Track Session" count type has been published in v4.0.0.

This feature made some refactoring necessary, hence the major version upgrade. There may well be some bugs. Please report any that you find. We're well past the point where I can regression test the entire plugin on my own.

**Comment by Rudgas** [comment]
Thank you so much!

I have been testing the last few days, and found only two minor things:
- Changing the title of a note (for the first time that session), adds wordcount to session wordcount.
- Deleting a document doesn't affect session word count
