### ISSUE TITLE
Store counts in properties

### ISSUE THREAD

**Issue by mmarschall** [isaaclyman/novel-word-count-obsidian#97]
I would love to query the counts with DataView.

One way to enable that would be to store the counts in properties in the files.

Most probably this would require a setting to decide whether or not the counts, which are selected to be shown in the file explorer, should be stored as properties and maybe even enable the user to decide on the property name.

**Comment by mmarschall** [comment]
There is a plugin called [Frontmatter Generator](https://github.com/HananoshikaYomaru/Obsidian-Frontmatter-Generator). It can dynamically access objects in Obsidian and update properties. In addition to the `data.json` file, is there a way to dynamically query the data similar to something like this: `folder: file.parent.path`? Or how could I read from the `data.json` file? Thanks a lot! I really appreciate your plugin and your help!

**Comment by isaaclyman** [comment]
I haven't read the code of Frontmatter Generator, but it looks like it uses the file metadata from Obsidian, so I wouldn't expect it to know about `data.json`.

I don't really know how to solve that problem without a custom script or plugin.
