### ISSUE TITLE
A lot of new logs in the console developer window with debug is not active

### ISSUE THREAD

**Issue by pubdigital** [isaaclyman/novel-word-count-obsidian#98]
**Description**

Every time i pulse some keys or after some thime there is a new log in the console developer window. This is happens after i update today my plugins. Sorry my english is not so good.

**Device**

Linux Ubuntu 22.04 LTS 

I simply delete de line 1669 in main.js and the problem stop. The line contain console.log(counts); inside the function updateDisplayedCounts. I don't know if it is correct to delete this line. I think this need to show only when debug mode is active.

I love the plugin
Thanks, a lot

**Comment by isaaclyman** [comment]
Whoops. You're right, fix incoming.

**Comment by isaaclyman** [comment]
Fixed in v3.12.1.
